In [1]:
import pandas as pd
import yfinance as yf
import re
import numpy as np

In [2]:
def getObjectiveClosePrice(underlyingData, date):
    # Gets the close price on a date given objective data. None if date DNE
    # Consider using a hash map.
    try:
        return float(underlyingData.loc[underlyingData['Date'] == date]['Close'])
    except:
        return None

def getOptionProfit(expireDate, strike):
    # Gets the profit of an option given its expiration date and strike price
    endPrice = getObjectiveClosePrice(underlyingData, expireDate)
    if endPrice == None:
        return 0
    return max(endPrice - strike, 0)    
    
def getAndProcessOneYearOptionData():
    # Creating masterDf 
    masterDf = pd.read_csv("data/aapl_eod_202101.txt")
    for i in range(2, 13):
        masterDf = masterDf.append(pd.read_csv("data/aapl_eod_2021" + str(i).zfill(2) + ".txt"), low_memory=False)
    
    # Dropping irrelevant columns
    cols_to_drop = [0, 1, 3, 6, 14, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
    masterDf.drop(masterDf.columns[cols_to_drop],axis=1,inplace=True)
    
    # Modifying column names for readability
    col_names = []
    for x in list(masterDf.columns):
        x = x.replace(' [', '').replace(']', '')
        col_names.append(x)
    masterDf.columns = col_names

    # Converting all but a few columns to numeric
    for i in range(len(col_names)):
        if i == 0 or i == 2 or i == 11:
            continue
        masterDf[col_names[i]] = pd.to_numeric(masterDf[col_names[i]], errors='coerce')
    
    # Stripping strings in problematic columns
    masterDf['QUOTE_DATE'] = masterDf['QUOTE_DATE'].str.strip()
    masterDf['C_SIZE'] = masterDf['C_SIZE'].str.strip()
    masterDf['EXPIRE_DATE'] = masterDf['EXPIRE_DATE'].str.strip()

    # Converting date columns to dates
    masterDf['EXPIRE_DATE'] = masterDf['EXPIRE_DATE'].astype('datetime64[ns]')
    masterDf['QUOTE_DATE'] = masterDf['QUOTE_DATE'].astype('datetime64[ns]')

    # Import underlying data and remove all options past the last date of underlying data
    underlyingData = pd.read_csv("data/AAPL.csv")
    masterDf = masterDf[~(masterDf['EXPIRE_DATE'] > '2022-02-25')]
    
    # Drop rows with NaN in them
    masterDf.dropna()
    
    return masterDf

In [29]:
df = getAndProcessOneYearOptionData()

C:\Users\David\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3338: DtypeWarning: Columns (13) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

In [30]:
df

,[QUOTE_UNIXTIME],[QUOTE_READTIME],[QUOTE_DATE],[QUOTE_TIME_HOURS],[UNDERLYING_LAST],[EXPIRE_DATE],[EXPIRE_UNIX],[DTE],[C_DELTA],[C_GAMMA],...,[P_LAST],[P_DELTA],[P_GAMMA],[P_VEGA],[P_THETA],[P_RHO],[P_IV],[P_VOLUME],[STRIKE_DISTANCE],[STRIKE_DISTANCE_PCT]
0,1609794000,2021-01-04 16:00,2021-01-04,16.0,129.45,2021-01-08,1610139600,4.0,1.00000,0.00000,...,0.01,-0.00016,0.00012,0.00026,-0.00351,0.00000,1.886900,0.000000,64.4,0.498
1,1609794000,2021-01-04 16:00,2021-01-04,16.0,129.45,2021-01-08,1610139600,4.0,1.00000,0.00000,...,0.01,-0.00058,0.00010,0.00064,-0.00404,0.00000,1.694120,1.000000,59.4,0.459
2,1609794000,2021-01-04 16:00,2021-01-04,16.0,129.45,2021-01-08,1610139600,4.0,1.00000,0.00000,...,0.02,-0.00074,0.00008,0.00012,-0.00406,-0.00040,1.514290,1.000000,54.4,0.421
3,1609794000,2021-01-04 16:00,2021-01-04,16.0,129.45,2021-01-08,1610139600,4.0,1.00000,0.00000,...,0.01,-0.00131,0.00018,0.00059,-0.00338,-0.00052,1.346060,1.000000,49.4,0.382
4,1609794000,2021-01-04 16:00,2021-01-04,16.0,129.45,2021-01-08,1610139600,4.0,1.00000,0.00000,...,0.01,-0.00084,0.00016,0.00041,-0.00399,0.00000,1.186820,26.000000,44.4,0.343
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19618,1640984400,2021-12-31 16:00,2021-12-31,16.0,177.58,2024-01-19,1705698000,749.0,0.32514,0.00481,...,67.15,-0.69907,0.00454,0.85800,-0.01497,-2.83536,0.261910,2.000000,57.4,0.323
19619,1640984400,2021-12-31 16:00,2021-12-31,16.0,177.58,2024-01-19,1705698000,749.0,0.29918,0.00479,...,71.00,-0.71411,0.00429,0.83246,-0.01490,-2.85386,0.262470,0.000000,62.4,0.351
19620,1640984400,2021-12-31 16:00,2021-12-31,16.0,177.58,2024-01-19,1705698000,749.0,0.29044,0.00460,...,77.22,-0.73252,0.00411,0.79928,-0.01395,-2.85516,0.260440,0.000000,67.4,0.380
19621,1640984400,2021-12-31 16:00,2021-12-31,16.0,177.58,2024-01-19,1705698000,749.0,0.27424,0.00442,...,79.45,-0.74070,0.00381,0.78144,-0.01363,-2.85812,0.265370,5.000000,72.4,0.408
19622,1640984400,2021-12-31 16:00,2021-12-31,16.0,177.58,2024-01-19,1705698000,749.0,0.24362,0.00415,...,88.00,-0.77269,0.00321,0.70962,-0.01174,-2.78468,0.258560,9.000000,82.4,0.464

In [2]:


def importDataMonth(n):
    return pd.read_csv("data/aapl_eod_2021" + n + ".txt")

objectiveData = pd.read_csv("data/AAPL.csv")

def getObjectiveClosePrice(objectiveData, date):
    try:
        return float(objectiveData.loc[objectiveData['Date'] == date]['Close'])
    except:
        return None

print(getObjectiveClosePrice(objectiveData, "2020-12-18"))
print(getObjectiveClosePrice(objectiveData, "2020-12-19"))
print(getObjectiveClosePrice(objectiveData, "2020-12-20"))
print(getObjectiveClosePrice(objectiveData, "2020-12-21"))


objectiveData

126.660004
None
None
128.229996

,Date,Open,High,Low,Close,Adj Close,Volume
0,2020-12-14,122.599998,123.349998,121.540001,121.779999,120.879852,79184500
1,2020-12-15,124.339996,127.900002,124.129997,127.879997,126.934753,157243700
2,2020-12-16,127.410004,128.369995,126.559998,127.809998,126.865265,98208600
3,2020-12-17,128.899994,129.580002,128.039993,128.699997,127.748703,94359800
4,2020-12-18,128.960007,129.100006,126.120003,126.660004,125.723770,192541500
...,...,...,...,...,...,...,...
298,2022-02-18,169.820007,170.539993,166.190002,167.300003,167.300003,82772700
299,2022-02-22,164.979996,166.690002,162.149994,164.320007,164.320007,91162800
300,2022-02-23,165.539993,166.149994,159.750000,160.070007,160.070007,90009200
301,2022-02-24,152.580002,162.850006,152.000000,162.740005,162.740005,141147500
302,2022-02-25,163.839996,165.119995,160.869995,164.850006,164.850006,91974200



<figure class="wp-block-table"><table><tbody><tr><td><strong>Field</strong></td><td><strong>Definition</strong></td><td><strong>Example</strong></td></tr><tr><td>QUOTE_UNIXTIME</td><td>Time of quote as a Unix Timestamp</td><td>1583508900</td></tr><tr><td>QUOTE_READTIME</td><td>Time of quote in a readable form (year-month-day hour:minute) [yyyy-mm-dd hh:MM)</td><td>2020-03-06 10:35</td></tr><tr><td>QUOTE_DATE</td><td>Date of quote in a readable form (year-month-day) [yyyy-mm-dd]</td><td>2020-03-06</td></tr><tr><td>QUOTE_TIME_HOURS</td><td>Time of quoted day in hours</td><td>10.58333</td></tr><tr><td>UNDERLYING_LAST</td><td>Last price of underlying asset</td><td>296.38</td></tr><tr><td>EXPIRE_DATE</td><td>Expiry date of contract in a readable form (year-month-day) [yyyy-mm-dd]</td><td>2020-09-18</td></tr><tr><td>EXPIRE_UNIX</td><td>Expiry date of contract as a Unix Timestamp</td><td>1600459200</td></tr><tr><td>DTE</td><td>Days till Expiry in hours (assumes options expire on expiry date at 16:00)</td><td>196.18</td></tr><tr><td>C_DELTA</td><td>Derived Option Greek: Delta of Call option</td><td>0.12682</td></tr><tr><td>C_GAMMA</td><td>Derived Option Greek: Gamma of Call option</td><td>0.00508</td></tr><tr><td>C_VEGA</td><td>Derived Option Greek: Vega of Call option</td><td>0.45103</td></tr><tr><td>C_THETA</td><td>Derived Option Greek: Theta of Call option</td><td>-0.01843</td></tr><tr><td>C_RHO</td><td>Derived Option Greek: Rho of Call option</td><td>0.184</td></tr><tr><td>C_IV</td><td>Implied Volatility of Call option</td><td>0.18953</td></tr><tr><td>C_VOLUME</td><td>Days traded volume of Call option</td><td>1</td></tr><tr><td>C_LAST</td><td>Last traded price of Call option</td><td>2.25</td></tr><tr><td>C_SIZE</td><td>Current size of Call option</td><td>113 x 100</td></tr><tr><td>C_BID</td><td>Bid price of Call option</td><td>2.05</td></tr><tr><td>C_ASK</td><td>Ask price of Call option</td><td>2.82</td></tr><tr><td>STRIKE</td><td>Option strike price</td><td>345</td></tr><tr><td>P_BID</td><td>Bid price of Put option</td><td>52.58</td></tr><tr><td>P_ASK</td><td>Ask price of Put option</td><td>54.68</td></tr><tr><td>P_SIZE</td><td>Current size of Put option</td><td>113 x 113</td></tr><tr><td>P_LAST</td><td>Last traded price of Put option</td><td>43</td></tr><tr><td>P_DELTA</td><td>Derived Option Greek: Delta of Put option</td><td>-0.95081</td></tr><tr><td>P_GAMMA</td><td>Derived Option Greek: Gamma of Put option</td><td>0.00277</td></tr><tr><td>P_VEGA</td><td>Derived Option Greek: Vega of Put option</td><td>0.16209</td></tr><tr><td>P_THETA</td><td>Derived Option Greek: Theta of Put option</td><td>-0.02739</td></tr><tr><td>P_RHO</td><td>Derived Option Greek: Rho of Put option</td><td>-1.80885</td></tr><tr><td>P_IV</td><td>Implied Volatility of Put option</td><td>0.12222</td></tr><tr><td>P_VOLUME</td><td>Days traded volume of Put option</td><td>6</td></tr><tr><td>STRIKE_DISTANCE</td><td>Distance between strike price and current underlying price</td><td>48.6</td></tr><tr><td>STRIKE_DISTANCE_PCT</td><td>Distance as a percentage between strike price and current underlying price</td><td>0.164</td></tr></tbody></table></figure>

In [3]:
janData = importDataMonth("01")

cols = [0, 1, 3, 6, 14, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
janData.drop(janData.columns[cols],axis=1,inplace=True)
# janData.drop(["[QUOTE_UNIXTIME]"])
janData

,[QUOTE_DATE],[UNDERLYING_LAST],[EXPIRE_DATE],[DTE],[C_DELTA],[C_GAMMA],[C_VEGA],[C_THETA],[C_RHO],[C_IV],[C_LAST],[C_SIZE],[C_BID],[C_ASK],[STRIKE],[STRIKE_DISTANCE],[STRIKE_DISTANCE_PCT]
0,2021-01-04,129.45,2021-01-08,4.00,1.00000,0.00000,0.00000,-0.00047,0.00866,,66.85,60 x 141,64.30,64.44,65.0,64.4,0.498
1,2021-01-04,129.45,2021-01-08,4.00,1.00000,0.00000,0.00000,0.00000,0.00951,,63.43,169 x 191,59.24,59.44,70.0,59.4,0.459
2,2021-01-04,129.45,2021-01-08,4.00,1.00000,0.00000,0.00000,-0.00047,0.01002,,54.15,60 x 159,54.24,54.40,75.0,54.4,0.421
3,2021-01-04,129.45,2021-01-08,4.00,1.00000,0.00000,0.00000,0.00000,0.01081,,48.91,70 x 195,49.25,49.40,80.0,49.4,0.382
4,2021-01-04,129.45,2021-01-08,4.00,1.00000,0.00000,0.00000,-0.00010,0.01178,,43.20,110 x 70,44.25,44.40,85.0,44.4,0.343
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20818,2021-01-29,131.74,2023-03-17,776.96,0.40257,0.00477,0.74407,-0.02056,0.76836,0.420950,15.70,57 x 318,15.69,18.36,185.0,53.3,0.404
20819,2021-01-29,131.74,2023-03-17,776.96,0.38692,0.00477,0.73533,-0.02031,0.74165,0.421150,15.30,154 x 486,14.74,17.44,190.0,58.3,0.442
20820,2021-01-29,131.74,2023-03-17,776.96,0.36524,0.00469,0.72344,-0.01924,0.71118,0.415160,14.70,31 x 5,14.15,15.44,195.0,63.3,0.480
20821,2021-01-29,131.74,2023-03-17,776.96,0.35009,0.00468,0.71248,-0.01887,0.68446,0.415200,13.80,111 x 20,13.45,14.45,200.0,68.3,0.518
20822,2021-01-29,131.74,2023-03-17,776.96,0.32266,0.00443,0.69029,-0.01807,0.63682,0.417600,12.45,14 x 5,12.15,13.04,210.0,78.3,0.594

In [4]:
col_names = []
for x in list(janData.columns):
    x = x.replace(' [', '')
    x = x.replace(']', '')
    col_names.append(x)
janData.columns = col_names

for i in range(len(col_names)):
    if i == 0 or i == 2 or i == 11:
        continue
    janData[col_names[i]] = pd.to_numeric(janData[col_names[i]], errors='coerce')

janData['QUOTE_DATE'] = janData['QUOTE_DATE'].str.strip()
janData['C_SIZE'] = janData['C_SIZE'].str.strip()
janData['EXPIRE_DATE'] = janData['EXPIRE_DATE'].str.strip()

janData

,QUOTE_DATE,UNDERLYING_LAST,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_LAST,C_SIZE,C_BID,C_ASK,STRIKE,STRIKE_DISTANCE,STRIKE_DISTANCE_PCT
0,2021-01-04,129.45,2021-01-08,4.00,1.00000,0.00000,0.00000,-0.00047,0.00866,NaN,66.85,60 x 141,64.30,64.44,65.0,64.4,0.498
1,2021-01-04,129.45,2021-01-08,4.00,1.00000,0.00000,0.00000,0.00000,0.00951,NaN,63.43,169 x 191,59.24,59.44,70.0,59.4,0.459
2,2021-01-04,129.45,2021-01-08,4.00,1.00000,0.00000,0.00000,-0.00047,0.01002,NaN,54.15,60 x 159,54.24,54.40,75.0,54.4,0.421
3,2021-01-04,129.45,2021-01-08,4.00,1.00000,0.00000,0.00000,0.00000,0.01081,NaN,48.91,70 x 195,49.25,49.40,80.0,49.4,0.382
4,2021-01-04,129.45,2021-01-08,4.00,1.00000,0.00000,0.00000,-0.00010,0.01178,NaN,43.20,110 x 70,44.25,44.40,85.0,44.4,0.343
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20818,2021-01-29,131.74,2023-03-17,776.96,0.40257,0.00477,0.74407,-0.02056,0.76836,0.42095,15.70,57 x 318,15.69,18.36,185.0,53.3,0.404
20819,2021-01-29,131.74,2023-03-17,776.96,0.38692,0.00477,0.73533,-0.02031,0.74165,0.42115,15.30,154 x 486,14.74,17.44,190.0,58.3,0.442
20820,2021-01-29,131.74,2023-03-17,776.96,0.36524,0.00469,0.72344,-0.01924,0.71118,0.41516,14.70,31 x 5,14.15,15.44,195.0,63.3,0.480
20821,2021-01-29,131.74,2023-03-17,776.96,0.35009,0.00468,0.71248,-0.01887,0.68446,0.41520,13.80,111 x 20,13.45,14.45,200.0,68.3,0.518
20822,2021-01-29,131.74,2023-03-17,776.96,0.32266,0.00443,0.69029,-0.01807,0.63682,0.41760,12.45,14 x 5,12.15,13.04,210.0,78.3,0.594

In [5]:
def getOptionProfit(expireDate, strike):
    endPrice = getObjectiveClosePrice(objectiveData, expireDate)
    if endPrice == None:
#         print('fuck')
        return 0
    return max(endPrice - strike, 0)

In [6]:
getOptionProfit("2021-01-08",65, 64.44)

2.610003000000006

In [6]:
janData['moneyMade'] = janData.apply(lambda x: getOptionProfit(x['EXPIRE_DATE'], x['STRIKE'], (x['C_BID'] + x['C_ASK'])/2), axis=1)

In [154]:
moneyMade = 0
for index, row in janData.iterrows():
    if index > 100:
        break
    moneyMade += getOptionProfit(row["EXPIRE_DATE"], row["STRIKE"], row["C_BID"])

In [9]:
janData['EXPIRE_DATE'] = janData['EXPIRE_DATE'].astype('datetime64[ns]')
janData['QUOTE_DATE'] = janData['QUOTE_DATE'].astype('datetime64[ns]')

In [11]:
janData

,QUOTE_DATE,UNDERLYING_LAST,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_LAST,C_SIZE,C_BID,C_ASK,STRIKE,STRIKE_DISTANCE,STRIKE_DISTANCE_PCT
0,2021-01-04,129.45,2021-01-08,4.00,1.00000,0.00000,0.00000,-0.00047,0.00866,NaN,66.85,60 x 141,64.30,64.44,65.0,64.4,0.498
1,2021-01-04,129.45,2021-01-08,4.00,1.00000,0.00000,0.00000,0.00000,0.00951,NaN,63.43,169 x 191,59.24,59.44,70.0,59.4,0.459
2,2021-01-04,129.45,2021-01-08,4.00,1.00000,0.00000,0.00000,-0.00047,0.01002,NaN,54.15,60 x 159,54.24,54.40,75.0,54.4,0.421
3,2021-01-04,129.45,2021-01-08,4.00,1.00000,0.00000,0.00000,0.00000,0.01081,NaN,48.91,70 x 195,49.25,49.40,80.0,49.4,0.382
4,2021-01-04,129.45,2021-01-08,4.00,1.00000,0.00000,0.00000,-0.00010,0.01178,NaN,43.20,110 x 70,44.25,44.40,85.0,44.4,0.343
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20818,2021-01-29,131.74,2023-03-17,776.96,0.40257,0.00477,0.74407,-0.02056,0.76836,0.42095,15.70,57 x 318,15.69,18.36,185.0,53.3,0.404
20819,2021-01-29,131.74,2023-03-17,776.96,0.38692,0.00477,0.73533,-0.02031,0.74165,0.42115,15.30,154 x 486,14.74,17.44,190.0,58.3,0.442
20820,2021-01-29,131.74,2023-03-17,776.96,0.36524,0.00469,0.72344,-0.01924,0.71118,0.41516,14.70,31 x 5,14.15,15.44,195.0,63.3,0.480
20821,2021-01-29,131.74,2023-03-17,776.96,0.35009,0.00468,0.71248,-0.01887,0.68446,0.41520,13.80,111 x 20,13.45,14.45,200.0,68.3,0.518
20822,2021-01-29,131.74,2023-03-17,776.96,0.32266,0.00443,0.69029,-0.01807,0.63682,0.41760,12.45,14 x 5,12.15,13.04,210.0,78.3,0.594

In [18]:
janData = janData[~(janData['EXPIRE_DATE'] > '2022-02-25')]

In [19]:
janData

,QUOTE_DATE,UNDERLYING_LAST,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_LAST,C_SIZE,C_BID,C_ASK,STRIKE,STRIKE_DISTANCE,STRIKE_DISTANCE_PCT
0,2021-01-04,129.45,2021-01-08,4.0,1.00000,0.00000,0.00000,-0.00047,0.00866,NaN,66.85,60 x 141,64.30,64.44,65.0,64.4,0.498
1,2021-01-04,129.45,2021-01-08,4.0,1.00000,0.00000,0.00000,0.00000,0.00951,NaN,63.43,169 x 191,59.24,59.44,70.0,59.4,0.459
2,2021-01-04,129.45,2021-01-08,4.0,1.00000,0.00000,0.00000,-0.00047,0.01002,NaN,54.15,60 x 159,54.24,54.40,75.0,54.4,0.421
3,2021-01-04,129.45,2021-01-08,4.0,1.00000,0.00000,0.00000,0.00000,0.01081,NaN,48.91,70 x 195,49.25,49.40,80.0,49.4,0.382
4,2021-01-04,129.45,2021-01-08,4.0,1.00000,0.00000,0.00000,-0.00010,0.01178,NaN,43.20,110 x 70,44.25,44.40,85.0,44.4,0.343
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20616,2021-01-29,131.74,2022-01-21,357.0,0.22813,0.00558,0.39473,-0.02332,0.23702,0.41674,6.00,1 x 17,5.95,6.00,195.0,63.3,0.480
20617,2021-01-29,131.74,2022-01-21,357.0,0.20946,0.00531,0.37561,-0.02213,0.21820,0.41638,5.44,11 x 41,5.30,5.40,200.0,68.3,0.518
20618,2021-01-29,131.74,2022-01-21,357.0,0.17817,0.00477,0.34066,-0.01996,0.18708,0.41724,4.55,333 x 21,4.30,4.50,210.0,78.3,0.594
20619,2021-01-29,131.74,2022-01-21,357.0,0.14419,0.00415,0.29656,-0.01746,0.15296,0.42558,3.35,52 x 20,3.41,3.50,225.0,93.3,0.708
20620,2021-01-29,131.74,2022-01-21,357.0,0.10448,0.00312,0.23623,-0.01436,0.11135,0.43899,2.41,30 x 31,2.36,2.46,250.0,118.3,0.898

In [24]:
janData.dropna()

,QUOTE_DATE,UNDERLYING_LAST,EXPIRE_DATE,DTE,C_DELTA,C_GAMMA,C_VEGA,C_THETA,C_RHO,C_IV,C_LAST,C_SIZE,C_BID,C_ASK,STRIKE,STRIKE_DISTANCE,STRIKE_DISTANCE_PCT
13,2021-01-04,129.45,2021-01-08,4.0,0.99330,0.00182,0.00267,-0.01615,0.01475,0.70653,24.30,97 x 100,23.39,23.56,106.0,23.4,0.181
16,2021-01-04,129.45,2021-01-08,4.0,0.99171,0.00236,0.00355,-0.01585,0.01479,0.61801,20.20,77 x 82,20.40,20.55,109.0,20.4,0.158
17,2021-01-04,129.45,2021-01-08,4.0,0.99211,0.00254,0.00301,-0.01615,0.01530,0.58957,19.40,95 x 186,19.41,19.55,110.0,19.4,0.150
18,2021-01-04,129.45,2021-01-08,4.0,0.98019,0.00493,0.00688,-0.04014,0.01468,0.65222,20.05,68 x 153,18.45,18.59,111.0,18.4,0.143
19,2021-01-04,129.45,2021-01-08,4.0,0.98415,0.00440,0.00543,-0.02860,0.01464,0.58313,21.28,60 x 20,17.44,17.55,112.0,17.4,0.135
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20616,2021-01-29,131.74,2022-01-21,357.0,0.22813,0.00558,0.39473,-0.02332,0.23702,0.41674,6.00,1 x 17,5.95,6.00,195.0,63.3,0.480
20617,2021-01-29,131.74,2022-01-21,357.0,0.20946,0.00531,0.37561,-0.02213,0.21820,0.41638,5.44,11 x 41,5.30,5.40,200.0,68.3,0.518
20618,2021-01-29,131.74,2022-01-21,357.0,0.17817,0.00477,0.34066,-0.01996,0.18708,0.41724,4.55,333 x 21,4.30,4.50,210.0,78.3,0.594
20619,2021-01-29,131.74,2022-01-21,357.0,0.14419,0.00415,0.29656,-0.01746,0.15296,0.42558,3.35,52 x 20,3.41,3.50,225.0,93.3,0.708
20620,2021-01-29,131.74,2022-01-21,357.0,0.10448,0.00312,0.23623,-0.01436,0.11135,0.43899,2.41,30 x 31,2.36,2.46,250.0,118.3,0.898

In [156]:
# To do for next time:
# Figure out how volatility will be measured. 
# Pull rates data
# Pull relevant data fields and normalize data